/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/clientes/{cliente_nit}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle del cliente */
        get: operations["detalle_api_v1_clientes__cliente_nit__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{cliente_nit}/gestiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial de gestiones del cliente */
        get: operations["gestiones_api_v1_clientes__cliente_nit__gestiones_get"];
        put?: never;
        /**
         * Registrar una gestion de cobranza
         * @description §11: el gestor registra la gestion y la alerta pasa a gestionada.
         *
         *     No toca el saldo ni el bucket. §16 separa el estado de la gestion del de la
         *     factura: una factura sigue vencida aunque ya se haya gestionado.
         */
        post: operations["registrar_gestion_api_v1_clientes__cliente_nit__gestiones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuracion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reglas y buckets vigentes */
        get: operations["obtener_api_v1_configuracion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuracion/auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial de cambios de configuracion */
        get: operations["historial_api_v1_configuracion_auditoria_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configuracion/reglas/{codigo}/parametros/{nombre}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Fijar el valor de un parametro
         * @description §8.4: solo usuarios autorizados modifican reglas. C-13 fija cual rol.
         */
        put: operations["fijar_api_v1_configuracion_reglas__codigo__parametros__nombre__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cortes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cortes disponibles */
        get: operations["listar_cortes_api_v1_cortes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ejecucion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bitacora de corridas */
        get: operations["bitacora_api_v1_ejecucion_get"];
        put?: never;
        /**
         * Ejecutar el motor para un corte
         * @description §10.2: reproceso manual. C-13 lo reserva al coordinador.
         */
        post: operations["ejecutar_api_v1_ejecucion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exportar/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Excel del corte */
        get: operations["a_excel_api_v1_exportar_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exportar/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** PDF del corte */
        get: operations["a_pdf_api_v1_exportar_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de gestion */
        get: operations["lista_api_v1_gestion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Panel de control */
        get: operations["panel_api_v1_panel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panel/criticos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clientes que requieren atencion */
        get: operations["criticos_api_v1_panel_criticos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quien soy
         * @description Permite al frontend recuperar la identidad sin volver a pedir la clave.
         */
        get: operations["quien_soy_api_v1_sesion_get"];
        put?: never;
        /** Iniciar sesion */
        post: operations["iniciar_api_v1_sesion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sonda de salud */
        get: operations["salud_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BarraAging
         * @description Un bucket en el grafico de antiguedad.
         */
        BarraAging: {
            /** Bucket */
            bucket: string;
            /** Color */
            color: string;
            /** Etiqueta */
            etiqueta: string;
            /** Facturas */
            facturas: number;
            /** Pct Sobre Total */
            pct_sobre_total: string;
            /** Saldo */
            saldo: string;
        };
        /** BucketConfigurado */
        BucketConfigurado: {
            /** Accion */
            accion: string;
            /** Activo */
            activo: boolean;
            /** Alerta */
            alerta: string | null;
            /** Codigo */
            codigo: string;
            /** Color */
            color: string;
            /** Desde */
            desde: number | null;
            /** Etiqueta */
            etiqueta: string;
            /** Hasta */
            hasta: number | null;
            /** Orden */
            orden: number;
            /** Prioridad Base */
            prioridad_base: number;
            /** Prioridad Etiqueta */
            prioridad_etiqueta: string;
        };
        /**
         * CambioParametro
         * @description Peticion para fijar un umbral.
         *
         *     Es el camino por el que R01 y R02 se activan: sin despliegue, con rastro.
         *     El usuario no viaja aqui: sale del token, porque un rastro que el cliente
         *     firma a su gusto no es un rastro.
         */
        CambioParametro: {
            /**
             * Valor
             * @description Valor nuevo. Se guarda como texto y la regla lo interpreta.
             */
            valor: string;
        };
        /** ClienteEnRanking */
        ClienteEnRanking: {
            /** Cartera Total */
            cartera_total: string;
            /** Cliente Nit */
            cliente_nit: string;
            /** Cliente Nombre */
            cliente_nombre: string;
            /** Dias Max */
            dias_max: number;
            /** Marcadores */
            marcadores?: string[];
            /** N Vencidas */
            n_vencidas: number;
            /** Pct 90 */
            pct_90: string;
            /** Pct Vencida */
            pct_vencida: string;
            /** Prioridad */
            prioridad: number;
            /** Prioridad Etiqueta */
            prioridad_etiqueta: string;
            /** Vencida */
            vencida: string;
        };
        /** Configuracion */
        Configuracion: {
            /** Buckets */
            buckets: components["schemas"]["BucketConfigurado"][];
            /** Empresa Id */
            empresa_id: string;
            /** Reglas */
            reglas: components["schemas"]["ReglaConfigurada"][];
            /** Version Parametros */
            version_parametros: string;
        };
        /**
         * Corte
         * @description Un corte disponible para consultar o reproducir.
         */
        Corte: {
            /** Cartera Total */
            cartera_total: string;
            /**
             * Corte
             * Format: date
             */
            corte: string;
            /**
             * Generado
             * Format: date-time
             */
            generado: string;
            /** N Clientes */
            n_clientes: number;
            /** Version Parametros */
            version_parametros: string;
        };
        /** Credenciales */
        Credenciales: {
            /** Clave */
            clave: string;
            /** Usuario */
            usuario: string;
        };
        /** DetalleCliente */
        DetalleCliente: {
            /** Alertas */
            alertas: components["schemas"]["FilaGestion"][];
            /** Cartera Total */
            cartera_total: string;
            /** Cliente Nit */
            cliente_nit: string;
            /** Cliente Nombre */
            cliente_nombre: string;
            /**
             * Corte
             * Format: date
             */
            corte: string;
            /** Dias Max */
            dias_max: number;
            /** Gestiones */
            gestiones?: components["schemas"]["Gestion"][];
            /** Marcadores */
            marcadores: string[];
            /** Mayor 150 */
            mayor_150: string;
            /** Mayor 90 */
            mayor_90: string;
            /** N Facturas */
            n_facturas: number;
            /** N Vencidas */
            n_vencidas: number;
            /** Pct 90 */
            pct_90: string;
            /** Pct Vencida */
            pct_vencida: string;
            /** Por Vencer */
            por_vencer: string;
            /** Prioridad */
            prioridad: number;
            /** Prioridad Etiqueta */
            prioridad_etiqueta: string;
            /** Vence Hoy */
            vence_hoy: string;
            /** Vencida */
            vencida: string;
        };
        /** Ejecucion */
        Ejecucion: {
            /** Alertas Cerradas */
            alertas_cerradas: number;
            /** Alertas Generadas */
            alertas_generadas: number;
            /**
             * Corte
             * Format: date
             */
            corte: string;
            /** Estado */
            estado: string;
            /** Filas Procesadas */
            filas_procesadas: number;
            /** Fin */
            fin: string | null;
            /**
             * Inicio
             * Format: date-time
             */
            inicio: string;
            /** Mensaje */
            mensaje: string | null;
        };
        /** EntradaAuditoria */
        EntradaAuditoria: {
            /** Campo */
            campo: string;
            /** Entidad */
            entidad: string;
            /**
             * Fecha Hora
             * Format: date-time
             */
            fecha_hora: string;
            /** Usuario Id */
            usuario_id: string;
            /** Valor Anterior */
            valor_anterior: string | null;
            /** Valor Nuevo */
            valor_nuevo: string | null;
        };
        /**
         * FilaGestion
         * @description Una linea de la bandeja de trabajo.
         */
        FilaGestion: {
            /** Accion */
            accion: string;
            /** Bucket */
            bucket: string | null;
            /** Cliente Nit */
            cliente_nit: string;
            /**
             * Cliente Nombre
             * @default
             */
            cliente_nombre: string;
            /** Codigo */
            codigo: string;
            /** Credito Aplicado */
            credito_aplicado: string | null;
            /** Dias */
            dias: number | null;
            /** Estado */
            estado: string;
            /** Etiqueta */
            etiqueta: string;
            /** Explicacion */
            explicacion: string | null;
            /** Factura */
            factura: string;
            /** Id */
            id: number;
            /** Prioridad */
            prioridad: number;
            /** Prioridad Etiqueta */
            prioridad_etiqueta: string;
            /** Saldo */
            saldo: string | null;
            /** Saldo Bruto */
            saldo_bruto: string | null;
            /** Vendedor */
            vendedor?: string | null;
            /** Zona */
            zona?: string | null;
        };
        /** Gestion */
        Gestion: {
            /** Cliente Nit */
            cliente_nit: string;
            /** Compromiso Fecha */
            compromiso_fecha: string | null;
            /** Compromiso Valor */
            compromiso_valor: string | null;
            /** Corte */
            corte: string | null;
            /** Factura */
            factura: string;
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /** Id */
            id: number;
            /** Observacion */
            observacion: string | null;
            /** Resultado */
            resultado: string | null;
            /** Tipo */
            tipo: string;
            /** Usuario Id */
            usuario_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ListaGestion */
        ListaGestion: {
            /**
             * Corte
             * Format: date
             */
            corte: string;
            /** Filas */
            filas: components["schemas"]["FilaGestion"][];
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
            /** Total */
            total: number;
        };
        /**
         * NuevaGestion
         * @description Lo que registra el gestor tras contactar al cliente.
         *
         *     El compromiso de pago es opcional, pero si va, van sus dos partes: media
         *     promesa no se puede seguir.
         */
        NuevaGestion: {
            /** Compromiso Fecha */
            compromiso_fecha?: string | null;
            /** Compromiso Valor */
            compromiso_valor?: number | string | null;
            /**
             * Factura
             * @description Vacio para una alerta de cliente.
             * @default
             */
            factura: string;
            /** Observacion */
            observacion?: string | null;
            /** Resultado */
            resultado?: string | null;
            /**
             * Tipo
             * @description llamada, correo, mensaje, visita, acuerdo, disputa u otra
             */
            tipo: string;
        };
        /**
         * Panel
         * @description Respuesta del panel: todo lo que §8.1 pide, en una sola llamada.
         */
        Panel: {
            /** Aging */
            aging: components["schemas"]["BarraAging"][];
            /**
             * Corte
             * Format: date
             */
            corte: string;
            /** Empresa Id */
            empresa_id: string;
            /** Generado */
            generado?: string | null;
            /** Kpis */
            kpis: components["schemas"]["TarjetaKPI"][];
            /** N Clientes */
            n_clientes: number;
            /** N Facturas */
            n_facturas: number;
            /** Ranking */
            ranking: components["schemas"]["ClienteEnRanking"][];
            /** Reglas Inactivas */
            reglas_inactivas?: {
                [key: string]: string;
            };
            /** Version Parametros */
            version_parametros?: string | null;
        };
        /** PeticionEjecucion */
        PeticionEjecucion: {
            /**
             * Corte
             * @description Corte a procesar. Si se omite, se usa la fecha de hoy en America/Bogota, que es la zona de referencia del motor (C-11).
             */
            corte?: string | null;
        };
        /** ReglaConfigurada */
        ReglaConfigurada: {
            /** Accion */
            accion: string;
            /** Activa */
            activa: boolean;
            /** Ambito */
            ambito: string;
            /** Codigo */
            codigo: string;
            /** Etiqueta */
            etiqueta: string;
            /** Faltantes */
            faltantes: string[];
            /** Motivo Inactiva */
            motivo_inactiva: string | null;
            /** Parametros */
            parametros: {
                [key: string]: string;
            };
            /** Parametros Requeridos */
            parametros_requeridos: string[];
            /** Prioridad */
            prioridad: number;
        };
        /** ResultadoEjecucion */
        ResultadoEjecucion: {
            /** Alertas Actualizadas */
            alertas_actualizadas: number;
            /** Alertas Cerradas */
            alertas_cerradas: number;
            /** Alertas Insertadas */
            alertas_insertadas: number;
            /** Clientes */
            clientes: number;
            /**
             * Corte
             * Format: date
             */
            corte: string;
            /** Empresa Id */
            empresa_id: string;
            /** Filas Leidas */
            filas_leidas: number;
            /** Reglas Inactivas */
            reglas_inactivas: {
                [key: string]: string;
            };
            /** Version Parametros */
            version_parametros: string;
        };
        /**
         * Sesion
         * @description Token de sesion y quien lo lleva.
         *
         *     El rol viaja para que el frontend pueda ocultar lo que el usuario no puede
         *     hacer. No es la comprobacion: esa la hace el servidor en cada peticion.
         */
        Sesion: {
            /** Empresa Id */
            empresa_id: string;
            /**
             * Expira
             * Format: date-time
             */
            expira: string;
            /** Nombre */
            nombre: string;
            /** Rol */
            rol: number;
            /** Rol Etiqueta */
            rol_etiqueta: string;
            /** Token */
            token: string;
            /** Usuario Id */
            usuario_id: string;
        };
        /**
         * TarjetaKPI
         * @description Cifra del encabezado con su peso sobre el total.
         *
         *     El porcentaje viaja calculado desde el servidor: si lo calculara el
         *     frontend seria una segunda implementacion del indicador, que es justo lo
         *     que §16 prohibe.
         */
        TarjetaKPI: {
            /** Codigo */
            codigo: string;
            /** Etiqueta */
            etiqueta: string;
            /** Pct Sobre Total */
            pct_sobre_total: string;
            /** Valor */
            valor: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    detalle_api_v1_clientes__cliente_nit__get: {
        parameters: {
            query?: {
                corte?: string | null;
            };
            header?: never;
            path: {
                cliente_nit: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleCliente"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gestiones_api_v1_clientes__cliente_nit__gestiones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_nit: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_gestion_api_v1_clientes__cliente_nit__gestiones_post: {
        parameters: {
            query?: {
                corte?: string | null;
            };
            header?: never;
            path: {
                cliente_nit: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NuevaGestion"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_api_v1_configuracion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Configuracion"];
                };
            };
        };
    };
    historial_api_v1_configuracion_auditoria_get: {
        parameters: {
            query?: {
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntradaAuditoria"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fijar_api_v1_configuracion_reglas__codigo__parametros__nombre__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
                nombre: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioParametro"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Configuracion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_cortes_api_v1_cortes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Corte"][];
                };
            };
        };
    };
    bitacora_api_v1_ejecucion_get: {
        parameters: {
            query?: {
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ejecucion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ejecutar_api_v1_ejecucion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionEjecucion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoEjecucion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    a_excel_api_v1_exportar_excel_get: {
        parameters: {
            query?: {
                corte?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    a_pdf_api_v1_exportar_pdf_get: {
        parameters: {
            query?: {
                corte?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lista_api_v1_gestion_get: {
        parameters: {
            query?: {
                prioridad_minima?: number | null;
                bucket?: string | null;
                vendedor?: string | null;
                zona?: string | null;
                estado?: string | null;
                /** @description NIT o numero de factura */
                busqueda?: string | null;
                orden?: string;
                pagina?: number;
                por_pagina?: number;
                corte?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaGestion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    panel_api_v1_panel_get: {
        parameters: {
            query?: {
                corte?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Panel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criticos_api_v1_panel_criticos_get: {
        parameters: {
            query?: {
                limite?: number;
                corte?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteEnRanking"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quien_soy_api_v1_sesion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sesion"];
                };
            };
        };
    };
    iniciar_api_v1_sesion_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credenciales"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sesion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    salud_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
